item {
  id: 13
  name: 'motorcyclist'
}

item {
  id: 14
  name: 'motorcyclist_pedestrian_road_violation'
}

item {
  id: 15
  name: 'motorcyclist_no_helmet_violation'
}

item {
  id: 16
  name: 'motorcyclist_jaywalking_violation'
}

item {
  id: 17
  name: 'motorcyclist_signal_violation'
}

item {
  id: 18
  name: 'motorcyclist_stop_line_violation'
}

item {
  id: 19
  name: 'motorcyclist_crosswalk_violation'
}